name: Publish to PyPI

on:
    release:
        types: [published] # "Publish release" on GitHubu

jobs:
    build-n-publish:
        name: Build and publish Python distro to PyPI
        runs-on: ubuntu-latest
        permissions:
            # Trusted Publishing (OIDC)
            id-token: write
            contents: read

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install build dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build

            - name: Build binary wheel and source tarball
              run: python -m build

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  # NO API TOKEN if configured in Trusted Publisher on PyPI
                  print-hash: true
